*** Comments ***
    AdoPet Landing Page Scenario
    This scenario is used to test the AdoPet landing page.
*** Variables ***
&{lading_page_displayed_correctly}           BUTTON_NAME_LADING_PAGE=${EMPTY}
&{lading_page_redirected_to_home}            BUTTON_NAME_LADING_PAGE=Ver pets disponíveis para adoção
&{lading_page_redirected_to_login}           BUTTON_NAME_LADING_PAGE=Cadastrar
&{lading_page_redirected_to_registration}    BUTTON_NAME_LADING_PAGE=Fazer login